version: '2'
services:
  php:
    image: php:7-apache
    restart: always
    links:
      - db:dockerdb
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:80
  db:
    restart: always
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
