version: '2'
services:
  httpd:
    restart: always
    image: httpd
    ports:
      - "80:80"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./www:/url/local/apache2/htdocs

  phpfpm:
    restart: always
    build: ./php-fpm-7
    links:
      - db:dockerdb
    volumes:
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./log/php-fpm:/var/log/php-fpm
      - ./www:/url/local/apache2/htdocs
  db:
    restart: always
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./mysql/databases:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
